[2024-12-17 18:30:12,586] 22 root - INFO - Initializing Gemini Embedding model...
[2024-12-17 18:30:12,588] 40 root - ERROR - An error occurred during the embedding process.
Traceback (most recent call last):
  File "c:\users\nysad\documents\qasystem\QAWithPDF\embedding.py", line 24, in download_gemini_embedding
    Settings.llm = model
  File "C:\Users\nysad\Documents\qasystem\venv\lib\site-packages\llama_index\core\settings.py", line 46, in llm
    self._llm = resolve_llm(llm)
  File "C:\Users\nysad\Documents\qasystem\venv\lib\site-packages\llama_index\core\llms\utils.py", line 64, in resolve_llm
    raise ValueError(
ValueError: llm must start with str 'local' or of type LLM or BaseLanguageModel
